python -u count_images_per_seq.py --scene=05-01-01-05-04 --cond=NIGHT-DAWN-WINTER-WINTERNIGHT-SOFTRAIN --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=04-01-04-05-05 --cond=NIGHT-WINTER-SOFTRAIN-WINTERNIGHT-FOG --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=01-05-05-04-04 --cond=WINTERNIGHT-WINTERNIGHT-NIGHT-SUNSET-WINTER --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=05-05-05-05-01 --cond=WINTERNIGHT-DAWN-NIGHT-SUNSET-WINTER --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=05-01-04-05-01 --cond=SOFTRAIN-NIGHT-FOG-WINTER-WINTERNIGHT --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=01-04-01-05-05 --cond=NIGHT-FOG-FALL-FALL-RAIN --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=04-05-04-01-04 --cond=SPRING-WINTER-NIGHT-DAWN-RAINNIGHT --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=01-04-04-01-05 --cond=WINTER-SUNSET-SPRING-SPRING-FOG --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=04-04-05-05-01 --cond=RAINNIGHT-SOFTRAIN-WINTER-FOG-DAWN --trg_dataset=SYNTHIA
python -u count_images_per_seq.py --scene=aachen-hamburg-frankfurt-munster --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=jena-hamburg-zurich-hanover --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=hamburg-stuttgart-tubingen-darmstadt --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=stuttgart-bochum-monchengladbach-bremen --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=lindau-bochum-aachen-stuttgart --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=monchengladbach-dusseldorf-jena-strasbourg --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=jena-strasbourg-bochum-dusseldorf --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=strasbourg-stuttgart-tubingen-monchengladbach --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=krefeld-erfurt-tubingen-strasbourg --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=monchengladbach-lindau-aachen-jena --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=zurich-darmstadt-dusseldorf-jena --cond=clean-fog-rain-fog --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=munster-hamburg-cologne-erfurt --cond=rain-fog-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=bremen-stuttgart-aachen-tubingen --cond=clean-fog-rain-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=dusseldorf-darmstadt-tubingen-bremen --cond=rain-clean-fog-rain --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=bremen-krefeld-lindau-bochum --cond=rain-clean-fog-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=cologne-munster-hanover-bremen --cond=clean-rain-fog-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=frankfurt-erfurt-zurich-cologne --cond=fog-rain-clean-clean --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=hanover-aachen-jena-munster --cond=clean-fog-fog-rain --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=bremen-ulm-zurich-darmstadt --cond=rain-fog-clean-fog --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=erfurt-ulm-aachen-lindau --cond=rain-clean-rain-fog --trg_dataset=Cityscapes
python -u count_images_per_seq.py --scene=GP010476-GP010402-GP030176-GP010376 --cond=fog-rain-snow-night --trg_dataset=ACDC
python -u count_images_per_seq.py --scene=GP010476-GOPR0351-GOPR0122-GP020402 --cond=fog-night-snow-rain --trg_dataset=ACDC
python -u count_images_per_seq.py --scene=GOPR0402-GP010376-GP010607-GOPR0478 --cond=rain-night-snow-fog --trg_dataset=ACDC
python -u count_images_per_seq.py --scene=GP040176-GP020402-GP020397-GP010476 --cond=snow-rain-night-fog --trg_dataset=ACDC
python -u count_images_per_seq.py --scene=GOPR0122-GP020475-GOPR0356-GP010402 --cond=snow-fog-night-rain --trg_dataset=ACDC
python -u save_labels_per_image.py --scene=05-01-01-05-04 --cond=NIGHT-DAWN-WINTER-WINTERNIGHT-SOFTRAIN --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=04-01-04-05-05 --cond=NIGHT-WINTER-SOFTRAIN-WINTERNIGHT-FOG --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=01-05-05-04-04 --cond=WINTERNIGHT-WINTERNIGHT-NIGHT-SUNSET-WINTER --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=05-05-05-05-01 --cond=WINTERNIGHT-DAWN-NIGHT-SUNSET-WINTER --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=05-01-04-05-01 --cond=SOFTRAIN-NIGHT-FOG-WINTER-WINTERNIGHT --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=01-04-01-05-05 --cond=NIGHT-FOG-FALL-FALL-RAIN --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=04-05-04-01-04 --cond=SPRING-WINTER-NIGHT-DAWN-RAINNIGHT --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=01-04-04-01-05 --cond=WINTER-SUNSET-SPRING-SPRING-FOG --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=04-04-05-05-01 --cond=RAINNIGHT-SOFTRAIN-WINTER-FOG-DAWN --trg_dataset=SYNTHIA
python -u save_labels_per_image.py --scene=aachen-hamburg-frankfurt-munster --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=jena-hamburg-zurich-hanover --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=hamburg-stuttgart-tubingen-darmstadt --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=stuttgart-bochum-monchengladbach-bremen --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=lindau-bochum-aachen-stuttgart --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=monchengladbach-dusseldorf-jena-strasbourg --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=jena-strasbourg-bochum-dusseldorf --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=strasbourg-stuttgart-tubingen-monchengladbach --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=krefeld-erfurt-tubingen-strasbourg --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=monchengladbach-lindau-aachen-jena --cond=clean-clean-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=zurich-darmstadt-dusseldorf-jena --cond=clean-fog-rain-fog --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=munster-hamburg-cologne-erfurt --cond=rain-fog-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=bremen-stuttgart-aachen-tubingen --cond=clean-fog-rain-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=dusseldorf-darmstadt-tubingen-bremen --cond=rain-clean-fog-rain --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=bremen-krefeld-lindau-bochum --cond=rain-clean-fog-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=cologne-munster-hanover-bremen --cond=clean-rain-fog-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=frankfurt-erfurt-zurich-cologne --cond=fog-rain-clean-clean --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=hanover-aachen-jena-munster --cond=clean-fog-fog-rain --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=bremen-ulm-zurich-darmstadt --cond=rain-fog-clean-fog --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=erfurt-ulm-aachen-lindau --cond=rain-clean-rain-fog --trg_dataset=Cityscapes
python -u save_labels_per_image.py --scene=GP010476-GP010402-GP030176-GP010376 --cond=fog-rain-snow-night --trg_dataset=ACDC
python -u save_labels_per_image.py --scene=GP010476-GOPR0351-GOPR0122-GP020402 --cond=fog-night-snow-rain --trg_dataset=ACDC
python -u save_labels_per_image.py --scene=GOPR0402-GP010376-GP010607-GOPR0478 --cond=rain-night-snow-fog --trg_dataset=ACDC
python -u save_labels_per_image.py --scene=GP040176-GP020402-GP020397-GP010476 --cond=snow-rain-night-fog --trg_dataset=ACDC
python -u save_labels_per_image.py --scene=GOPR0122-GP020475-GOPR0356-GP010402 --cond=snow-fog-night-rain --trg_dataset=ACDC
python run_available_benchmarks.py 
